# Generated by Django 3.0.5 on 2020-05-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=40)),
                ('userName', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('mailId', models.CharField(max_length=40)),
                ('phone', models.IntegerField(max_length=40)),
                ('age', models.IntegerField(max_length=40)),
            ],
        ),
    ]
